version: '3.3'

services:
  nalma:
    build:
      context: .
      dockerfile: nalma_dockerfile
    command: uvicorn services.gateway.app:app --host 0.0.0.0 --port 6432
    ports:
      - '6432:6432'
    env_file:
      - ./docker.env